### ISSUE TITLE
Extensibilidad

### ISSUE THREAD

**Issue by gonziesc** [NicoleChavez/TPs-Individuales-PdeP-2021#2]
https://github.com/NicoleChavez/TPs-Individuales-PdeP-2021/blob/bf7377c9935dc58fa44d1df8ee38af9ea880de48/tpMonopoly.hs#L65

Qué pasa si se agregan nuevas condiciones para ganar la subasta? Hay alguna mejor manela de modelar esto para que sea más fácil agregar tácticas ganadoras?

**Comment by NicoleChavez** [comment]
No se si entendí bien lo que había  que corregir pero trate de cambiar un poco la función!

**Comment by gonziesc** [comment]
Apuntaba a usar pattern matching! De esa forma, agregar nuevos casos seria más sencillo
