### ISSUE TITLE
Declaratividad

### ISSUE THREAD

**Issue by gonziesc** [NicoleChavez/TPs-Individuales-PdeP-2021#4]
https://github.com/NicoleChavez/TPs-Individuales-PdeP-2021/blob/bf7377c9935dc58fa44d1df8ee38af9ea880de48/tpMonopoly.hs#L78

Este punto quedó muy dificil de seguir. Fijate de delegar en funciones auxiliares. Además, es la mejor forma de hacerlo? Pensá si con otras abstracciones logras modelar mejor el punto y si no lo charlamos por acá.

**Comment by NicoleChavez** [comment]
En esta función trate de arreglarla un poco pero creo que se podría hacer mejor pero no se me ocurrió otra forma :/

**Comment by gonziesc** [comment]
Una primer abstracción podría haber sido para saber cuanto se cobra por cada alquiler:

`
alquileres unaPropiedad            
  |esPropiedadBarata unaPropiedad = 10            
  |otherwise                      = 20
`

Usando esta función, con sum y map salía más declarativo
